name: Test Coverage Enforcement

on:
  pull_request:
    branches: [ main, master ]  # Covers both common default branches

jobs:
  coverage-check:
    name: Verify 100% Test Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Prevent hanging jobs
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for proper Git history analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'  # Faster builds with caching

      - name: Run Tests with JaCoCo
        run: |
          ./gradlew clean test jacocoTestReport jacocoTestCoverageVerification
          # Fail if coverage < 100%
          ./gradlew jacocoTestCoverageVerification

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        if: always()  # Upload even if tests fail
        with:
          name: jacoco-coverage-report
          path: |
            build/reports/jacoco/test/html/
            build/reports/jacoco/test.xml
